### ISSUE TITLE
GitHub integration

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/thenewboston-Backend#108]
Create a periodic task using the Celery Beat scheduler that runs every 5 minutes. This will poll the GitHub API to fetch any PRs that have been merged into any of these repos: https://github.com/thenewboston-developers

For each PR, we will use an LLM to determine the value of the PR. **Note that you do not have to write this part. I am currently working on it. For development you can just generate a random number from 100-1,000 instead.**

Once the value has been determined, we will create a contribution to reward the contributor with that many coins. This will also increase the amount in the TNB wallet:

- https://github.com/thenewboston-developers/thenewboston-Backend/blob/master/thenewboston/contributions/models/contribution.py
- https://github.com/thenewboston-developers/thenewboston-Backend/blob/master/thenewboston/wallets/models/wallet.py

Our `GitHubUser` model will be used as the link between GitHub user and thenewboston user. When a GitHub PR is submitted and value assessed, we will look for a `GitHubUser` with the matching `GitHubUser.github_id` (GitHub user ID) and reward the `GitHubUser.reward_recipient` (thenewboston user) that amount. Later we will develop a system to update the `GitHubUser` dynamically, however for now we can just manually create them for development.

From a user's point of view, this will allow developers to work on the project and be rewarded for their contributions.

<img width="1365" alt="Screen Shot 2024-03-24 at 5 04 38 PM" src="https://github.com/thenewboston-developers/thenewboston-Backend/assets/8547538/f9cbd9a8-2f80-4962-90d7-06050346533b">

**Comment by dmugtasimov** [comment]
This is comment will collect the task break down (updatable):
1. Add Celery Beat
2. Implement Github client (based on https://github.com/PyGithub/PyGithub )

**Comment by dmugtasimov** [comment]
@buckyroberts I will implement the github integration with Personal access token to for (fine-grained or classic if it works). But there is an option to implement it as GitHub App. I do not know if there any benefits of that in this particular case. Please, let me know if you want me to explore that path

**Comment by dmugtasimov** [comment]
@buckyroberts There is already a model `thenewboston.github.models.repo.Repo`. How is it populated?
I can get a list of repos from GET https://api.github.com/orgs/thenewboston-developers/repos API call. Should add `Repo` instances from the API response? Or should I assume Repo prepopulated (I do not think so, since there just `name` attribute and I am not sure how well "machine readable" it is). Or maybe you do not expect to interact with persisted repos as a part of this task?

**Comment by dmugtasimov** [comment]
@buckyroberts There is also `pull_request` webhook available https://docs.github.com/en/webhooks/webhook-events-and-payloads#pull_request . One drawback of the webhooks is that in a rare case they can be lost due network or temporary service unavailability issues (therefore we will need to poll anyway, but can do it much less frequently) and they are harder to implement than active polling, but they allow to get events earlier and reduce network load. Please, let me know it you want me to explore that path

**Comment by dmugtasimov** [comment]
WIP branch: https://github.com/thenewboston-developers/thenewboston-Backend/tree/108-github-integration
