### ISSUE TITLE
Implement thenewboston.github.models.pull.Pull.value_points

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/thenewboston-Backend#119]
Add logic from https://github.com/buckyroberts/Value/blob/master/main.py

**Comment by dmugtasimov** [comment]
WIP branch: https://github.com/thenewboston-developers/thenewboston-Backend/tree/119-implement-thenewbostongithubmodelspullpullvalue_points

**Comment by dmugtasimov** [comment]
@buckyroberts implemented here: https://github.com/thenewboston-developers/thenewboston-Backend/pull/123
Please, review. It is OK if you merge and deploy once approved or I can do it, just let me know.
