### ISSUE TITLE
Return https in prod

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/thenewboston-Backend#133]
For the paginated responses return `https` in prod.

<img width="815" alt="Screen Shot 2024-04-13 at 6 31 50 PM" src="https://github.com/thenewboston-developers/thenewboston-Backend/assets/8547538/c4a48e8c-8955-4140-a73c-42035ebe9331">

**Comment by MAbdurrehman1** [comment]
I think setting `SECURE_PROXY_SSL_HEADER` may fix this.
ref link: https://docs.djangoproject.com/en/5.0/ref/settings/#secure-proxy-ssl-header

**Comment by dmugtasimov** [comment]
Started working on this one

**Comment by MAbdurrehman1** [comment]
@dmugtasimov Great Work 🚀 

Question: In order to test it locally, did you run your local setup on HTTPS? If yes, then how? via ngrok or setting up guicorn locally or by some other way?

**Comment by dmugtasimov** [comment]
@MAbdurrehman1 Locally I just tested that non-HTTPs access return non-HTTPs URLs. Then I checked nginx configuration in production for specifying the required header, deployed to production and tested it in production.

btw, we are using `daphne` in production. There is `run-daphne` Makefile target if you are interested

**Comment by MAbdurrehman1** [comment]
@dmugtasimov Sounds great!
Thank you.
