### ISSUE TITLE
Every PR merged into master should become a contribution

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/thenewboston-Backend#134]
Update the logic so that every PR merged into master becomes a contribution.

<img width="1108" alt="Screen Shot 2024-04-13 at 6 41 49 PM" src="https://github.com/thenewboston-developers/thenewboston-Backend/assets/8547538/f25d445e-cd5a-4b0b-843d-3271812a92a9">

<img width="1110" alt="Screen Shot 2024-04-13 at 6 42 05 PM" src="https://github.com/thenewboston-developers/thenewboston-Backend/assets/8547538/62e7c7bc-9ae3-49e4-8101-54bb622e0d31">

<img width="1441" alt="Screen Shot 2024-04-13 at 6 42 26 PM" src="https://github.com/thenewboston-developers/thenewboston-Backend/assets/8547538/13357756-ede2-4f76-8178-0ac3798984e8">

**Comment by dmugtasimov** [comment]
Implemented here: https://github.com/thenewboston-developers/thenewboston-Backend/pull/172
