### ISSUE TITLE
Ia is no longer responding to messages

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/thenewboston-Backend#137]
<img width="1383" alt="Screen Shot 2024-04-14 at 9 14 19 PM" src="https://github.com/thenewboston-developers/thenewboston-Backend/assets/8547538/14b9426d-4046-4209-92b3-7a755f0c8a7d">

**Comment by dmugtasimov** [comment]
@buckyroberts started working on this one

**Comment by dmugtasimov** [comment]
@buckyroberts please, feel free to close this one
