### ISSUE TITLE
Deployment issues

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/thenewboston-Backend#151]
When going through the deployment guide, got an error at this step.

<img width="1167" alt="Screen Shot 2024-04-21 at 11 51 53 AM" src="https://github.com/thenewboston-developers/thenewboston-Backend/assets/8547538/2343d519-3f57-450d-95a9-1c4c3cb971fb">

**Comment by dmugtasimov** [comment]
@buckyroberts you need to upgrade docker. Please, see my note here: https://github.com/thenewboston-developers/thenewboston-Backend/pull/130 :

```
@buckyroberts @MAbdurrehman1 you will need to upgrade docker compose to at least version 2.24 (we need it to allow optional .env file for docker compose, previously some workaround were used instead) locally once this PR will be merged. I will take care about upgrading on production
```

Also https://github.com/thenewboston-developers/thenewboston-Backend/blob/master/DEPLOY.md does no say to use `docker-compose` , a make target which in turn uses `docker compose` (notice no hyphen there, this way the docker compose is used as plug in, but with hyphen as a separate CLI tool and it is different version)

**Comment by dmugtasimov** [comment]
@buckyroberts also there is no longer `docker-compose` in the larger EC2 instance, just the plug in:
```
ubuntu@ip-172-31-39-220:~/thenewboston-Backend$ docker-compose --version
Command 'docker-compose' not found, but can be installed with:
sudo snap install docker          # version 24.0.5, or
sudo apt  install docker-compose  # version 1.29.2-1
See 'snap info docker' for additional versions.

ubuntu@ip-172-31-39-220:~/thenewboston-Backend$ docker compose version
Docker Compose version v2.26.1
```

**Comment by dmugtasimov** [comment]
I suggest to close this issue
