### ISSUE TITLE
Profile page elements endpoint

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/thenewboston-Backend#164]
Create an endpoint to send back the following stats for a given user:
- default wallet (TNB) balance
- amount following
- amount followers

Front end portion of this ticket: https://github.com/thenewboston-developers/thenewboston-Frontend/issues/184

**Comment by MAbdurrehman1** [comment]
@buckyroberts I think we should update the existing get user endpoint and include these stats in it instead of creating a completely separate endpoint.

What do you think?

**Comment by MAbdurrehman1** [comment]
>  I think we should update the existing get user endpoint and include these stats in it instead of creating a completely separate endpoint.
What do you think?

Nevermind! Now I understand creating a separate endpoint would be more suitable 🤣
