### ISSUE TITLE
Create contributions endpoint

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/thenewboston-Backend#166]
Update to the contribution model as well to allow for non-GitHub contributions. Also need to add a filter to allow users to query only their contributions.

https://github.com/thenewboston-developers/thenewboston-Frontend/issues/204

**Comment by dmugtasimov** [comment]
@buckyroberts please, review https://github.com/thenewboston-developers/thenewboston-Backend/pull/194

**Comment by dmugtasimov** [comment]
@buckyroberts should we close this one?
