### ISSUE TITLE
Latest contributions are not showing up

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/thenewboston-Backend#173]
There are contributions in the database that are not showing up on https://thenewboston.com/contributions

---

<img width="1387" alt="Screen Shot 2024-04-29 at 7 17 50 PM" src="https://github.com/thenewboston-developers/thenewboston-Backend/assets/8547538/919b5abc-6a7a-4f3b-9e1f-a715e7684668">

---

<img width="1130" alt="Screen Shot 2024-04-29 at 7 18 04 PM" src="https://github.com/thenewboston-developers/thenewboston-Backend/assets/8547538/3bea3542-d562-435a-aa37-28ed5e8bc029">

**Comment by MAbdurrehman1** [comment]
That's strange.
Let me look
