### ISSUE TITLE
Total Contributions by day

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/thenewboston-Backend#187]
Right now this contributions chart pulls down all contributions from the backend for the data needed to render the chart, which is becoming really slow. Instead, we need a custom endpoint on the backend to provide this data. The endpoint will aggregate the contribution amounts into days. So for each day, the total contributions are equal to the contributions from that day plus all other contributions before it. So that chart will always be constantly increasing.

<img width="815" alt="Screen Shot 2024-05-12 at 5 25 05 PM" src="https://github.com/thenewboston-developers/thenewboston-Backend/assets/8547538/faa19aab-1e4f-4f6d-a7f8-2ed97530ffb3">

**Comment by MAbdurrehman1** [comment]
@buckyroberts This was done in this PR https://github.com/thenewboston-developers/thenewboston-Backend/pull/209, so closing this issue.
