### ISSUE TITLE
Certain lectures not working

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/thenewboston-Backend#200]
On various lectures, the video player is not working.

<img width="1591" alt="Screen Shot 2024-05-23 at 8 18 30 PM" src="https://github.com/thenewboston-developers/thenewboston-Frontend/assets/8547538/e548948c-8a75-403f-b38d-a2e9fc2e1cc1">

**Comment by MAbdurrehman1** [comment]
@buckyroberts yeah, Betsegaw is right.
Invalid youtube IDs have been entered. I think, we need to get these corrected. 

<img width="416" alt="image" src="https://github.com/thenewboston-developers/thenewboston-Backend/assets/52558124/80e02000-4963-4c27-a222-e3c8926529da">

<img width="441" alt="image" src="https://github.com/thenewboston-developers/thenewboston-Backend/assets/52558124/3c222327-7c0d-452b-a0c0-3a0a689ec928">

<img width="364" alt="image" src="https://github.com/thenewboston-developers/thenewboston-Backend/assets/52558124/9fe54f09-8cd0-484e-b42e-7ddbc635ff84">

ps: These are my thoughts on the PR linked with this issue: https://github.com/thenewboston-developers/thenewboston-Backend/pull/211#issuecomment-2164169460

I'm going to close this ticket, but if you think that we do need to add some sort of validation, then please feel free to reopen it.
