### ISSUE TITLE
Anthropic support

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/thenewboston-Backend#221]
Make sure our prompt template system supports Anthropic and then set the model of the `create-response` template to `claude-3-5-sonnet-20240620`. Make sure to move the `prod` label for our system to pull down the correct prompt template.

<img width="714" alt="Screenshot 2024-08-07 at 9 38 39 AM" src="https://github.com/user-attachments/assets/b93b1805-9425-4fef-b641-3f133e720500">

**Comment by dmugtasimov** [comment]
Implemented here: https://github.com/thenewboston-developers/thenewboston-Backend/pull/222

**Comment by dmugtasimov** [comment]
@buckyroberts please, close if considered done
